language: ruby
rvm:
- 1.9.3
notifications:
  email: false
bundler_args: --deployment
script:
- bundle exec rake db:migrate
- bundle exec rake spec
env:
  global:
  - secure: Ch6JzqQoZs1hzWhxJ/VYYQuIovxsxISFu4/uCoQlplqhWWJ50epP/KyaNKjHyTIAmFfX2gGYF4tCw70fSII1Mvl/lp5aR46JdC1RC79H1n9usJv8GyKWtgcCBSV/cxAeo+XPfKGEgR07loND7AY0u5Mj+ToKwO0zzNzgqvknsTI=
-after_success:
 -- ./heroku.sh
