require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnumviewsController do

  # This should return the minimal set of attributes required to create a valid
  # Enumview. As you add validations to Enumview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "gender" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnumviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all enumviews as @enumviews" do
      enumview = Enumview.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enumviews).should eq([enumview])
    end
  end

  describe "GET show" do
    it "assigns the requested enumview as @enumview" do
      enumview = Enumview.create! valid_attributes
      get :show, {:id => enumview.to_param}, valid_session
      assigns(:enumview).should eq(enumview)
    end
  end

  describe "GET new" do
    it "assigns a new enumview as @enumview" do
      get :new, {}, valid_session
      assigns(:enumview).should be_a_new(Enumview)
    end
  end

  describe "GET edit" do
    it "assigns the requested enumview as @enumview" do
      enumview = Enumview.create! valid_attributes
      get :edit, {:id => enumview.to_param}, valid_session
      assigns(:enumview).should eq(enumview)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Enumview" do
        expect {
          post :create, {:enumview => valid_attributes}, valid_session
        }.to change(Enumview, :count).by(1)
      end

      it "assigns a newly created enumview as @enumview" do
        post :create, {:enumview => valid_attributes}, valid_session
        assigns(:enumview).should be_a(Enumview)
        assigns(:enumview).should be_persisted
      end

      it "redirects to the created enumview" do
        post :create, {:enumview => valid_attributes}, valid_session
        response.should redirect_to(Enumview.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enumview as @enumview" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enumview.any_instance.stub(:save).and_return(false)
        post :create, {:enumview => { "gender" => "invalid value" }}, valid_session
        assigns(:enumview).should be_a_new(Enumview)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enumview.any_instance.stub(:save).and_return(false)
        post :create, {:enumview => { "gender" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enumview" do
        enumview = Enumview.create! valid_attributes
        # Assuming there are no other enumviews in the database, this
        # specifies that the Enumview created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Enumview.any_instance.should_receive(:update_attributes).with({ "gender" => "" })
        put :update, {:id => enumview.to_param, :enumview => { "gender" => "" }}, valid_session
      end

      it "assigns the requested enumview as @enumview" do
        enumview = Enumview.create! valid_attributes
        put :update, {:id => enumview.to_param, :enumview => valid_attributes}, valid_session
        assigns(:enumview).should eq(enumview)
      end

      it "redirects to the enumview" do
        enumview = Enumview.create! valid_attributes
        put :update, {:id => enumview.to_param, :enumview => valid_attributes}, valid_session
        response.should redirect_to(enumview)
      end
    end

    describe "with invalid params" do
      it "assigns the enumview as @enumview" do
        enumview = Enumview.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enumview.any_instance.stub(:save).and_return(false)
        put :update, {:id => enumview.to_param, :enumview => { "gender" => "invalid value" }}, valid_session
        assigns(:enumview).should eq(enumview)
      end

      it "re-renders the 'edit' template" do
        enumview = Enumview.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enumview.any_instance.stub(:save).and_return(false)
        put :update, {:id => enumview.to_param, :enumview => { "gender" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enumview" do
      enumview = Enumview.create! valid_attributes
      expect {
        delete :destroy, {:id => enumview.to_param}, valid_session
      }.to change(Enumview, :count).by(-1)
    end

    it "redirects to the enumviews list" do
      enumview = Enumview.create! valid_attributes
      delete :destroy, {:id => enumview.to_param}, valid_session
      response.should redirect_to(enumviews_url)
    end
  end

end
